### ISSUE TITLE
CT Step 2: Roadmap & Plan Part 1 - Roadmap

### ISSUE THREAD

**Issue by thegoodman99** [paladinarcher/CT-Template#3]
**Description**
The second step of continuous testing is to roadmap & plan. Part 1 focuses on establishing a roadmap. Using the information gained from the continuous testing assessment, create a roadmap. This roadmap will help identify tools, define version control, define continuous integration, and validate current manual & automated tests.
**Acceptance Criteria**
- [ ] Documentation of the Roadmap including information on:

  - [ ]  identify tools
  - [ ] define version control
  - [ ] define continuous integration
  - [ ] validate current manual & automated tests
