### ISSUE TITLE
CT Step 2: Roadmap & Plan Part 2 - Plan

### ISSUE THREAD

**Issue by thegoodman99** [paladinarcher/CT-Template#4]
**Description**
The second step of continuous testing is to roadmap & plan part 2. Part 2 focuses on establishing a plan. Using the information gained from the continuous testing assessment and roadman, create a CT plan. This plan will include task delegation, setting up documentation, defining standard operating procedures, and defining new tests, data, mocks, & work items.   

**Acceptance Criteria**
- [ ] Documentation of the Plan including information on:

  - [ ] task delegation
  - [ ] document continuous testing system
  - [ ] define continuous testing SOP
  - [ ] define new tests, data, mocks, works items
  - [ ] Throw these into a word doc on P&A and PDMP sharepoint
